### ISSUE TITLE
Scala PR validation is failing (problem with org.scala-refactoring.update-site)

### ISSUE THREAD

**Issue by SethTisue** [scala-ide/uber-build#82]
a typical failure is:

```
[INFO] Adding repository file:/home/jenkins/workspace/scala-2.11.x-integrate-ide/target/scala-refactoring/org.scala-refactoring.update-site/target/site
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'scala-refactoring' from location file:/home/jenkins/workspace/scala-2.11.x-integrate-ide/target/scala-refactoring/org.scala-refactoring.update-site/target/site: No repository found at file:/home/jenkins/workspace/scala-2.11.x-integrate-ide/target/scala-refactoring/org.scala-refactoring.update-site/target/site. -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'scala-refactoring' from location file:/home/jenkins/workspace/scala-2.11.x-integrate-ide/target/scala-refactoring/org.scala-refactoring.update-site/target/site
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Failed to load p2 repository with ID 'scala-refactoring' from location file:/home/jenkins/workspace/scala-2.11.x-integrate-ide/target/scala-refactoring/org.scala-refactoring.update-site/target/site
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:301)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits(TargetPlatformFactoryImpl.java:269)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:174)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:126)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
	at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:82)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:215)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:99)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	... 11 more
Caused by: org.eclipse.equinox.p2.core.ProvisionException: No repository found at file:/home/jenkins/workspace/scala-2.11.x-integrate-ide/target/scala-refactoring/org.scala-refactoring.update-site/target/site.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:692)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:59)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:52)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:297)
	... 21 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: pr-scala-integrate-ide@typesafe.com
Notifying endpoint 'HTTP:http://scala-ci.typesafe.com:8888/jenkins'
Finished: FAILURE
```

it doesn't seem related to the content of the PR; there are multiple examples, e.g. https://github.com/scala/scala/pull/4728, https://github.com/scala/scala/pull/4725

**Comment by SethTisue** [comment]
@sschaef any idea what's going on here?

**Comment by SethTisue** [comment]
@sschaef: @adriaanm thinks https://github.com/scala-ide/scala-refactoring/pull/92 could be related?

**Comment by SethTisue** [comment]
especially https://github.com/scala-ide/scala-refactoring/commit/0ccc49c6e8ec61535d25d4cf8f9b0133e34bb77d#diff-600376dffeb79835ede4a0b285078036L49

**Comment by sschaef** [comment]
This is indeed a problem with uber-build. I'm going to fix it.

**Comment by dragos** [comment]
Let's revert that change in the meantime, so the Scala team is not blocked by these failures.

**Comment by SethTisue** [comment]
reverted in https://github.com/scala-ide/scala-refactoring/pull/95

**Comment by SethTisue** [comment]
test rebuild: https://github.com/scala/scala/pull/4728

**Comment by sschaef** [comment]
@SethTisue This is not yet merged because this didn't yet solve the problem

**Comment by SethTisue** [comment]
oops, I see I wasn't paying close enough attention.

**Comment by sschaef** [comment]
@SethTisue please rerun the Scala build, the fix is now merged. I tested uber-build locally, it should work.

Since the update site should be removed from scala-refactoring I let this issue open until uber-build is fixed to handle the change.

**Comment by SethTisue** [comment]
rebuild in progress at https://github.com/scala/scala/pull/4728

**Comment by SethTisue** [comment]
Scala PR validation working again. thanks Simon!
